#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-org.apache.felix.bundlerepository
Version  : 1.6.2
Release  : 1
URL      : https://repo1.maven.org/maven2/org/apache/felix/org.apache.felix.bundlerepository/1.6.2/org.apache.felix.bundlerepository-1.6.2.jar
Source0  : https://repo1.maven.org/maven2/org/apache/felix/org.apache.felix.bundlerepository/1.6.2/org.apache.felix.bundlerepository-1.6.2.jar
Source1  : https://repo1.maven.org/maven2/org/apache/felix/org.apache.felix.bundlerepository/1.6.2/org.apache.felix.bundlerepository-1.6.2.pom
Source2  : https://repo1.maven.org/maven2/org/apache/felix/org.apache.felix.bundlerepository/1.6.6/org.apache.felix.bundlerepository-1.6.6.jar
Source3  : https://repo1.maven.org/maven2/org/apache/felix/org.apache.felix.bundlerepository/1.6.6/org.apache.felix.bundlerepository-1.6.6.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 MIT
Requires: mvn-org.apache.felix.bundlerepository-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-org.apache.felix.bundlerepository package.
Group: Data

%description data
data components for the mvn-org.apache.felix.bundlerepository package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/felix/org.apache.felix.bundlerepository/1.6.2
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/apache/felix/org.apache.felix.bundlerepository/1.6.2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/felix/org.apache.felix.bundlerepository/1.6.2
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/apache/felix/org.apache.felix.bundlerepository/1.6.2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/felix/org.apache.felix.bundlerepository/1.6.6
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/apache/felix/org.apache.felix.bundlerepository/1.6.6

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/felix/org.apache.felix.bundlerepository/1.6.6
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/apache/felix/org.apache.felix.bundlerepository/1.6.6


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/apache/felix/org.apache.felix.bundlerepository/1.6.2/org.apache.felix.bundlerepository-1.6.2.jar
/usr/share/java/.m2/repository/org/apache/felix/org.apache.felix.bundlerepository/1.6.2/org.apache.felix.bundlerepository-1.6.2.pom
/usr/share/java/.m2/repository/org/apache/felix/org.apache.felix.bundlerepository/1.6.6/org.apache.felix.bundlerepository-1.6.6.jar
/usr/share/java/.m2/repository/org/apache/felix/org.apache.felix.bundlerepository/1.6.6/org.apache.felix.bundlerepository-1.6.6.pom
